fix issue #11: add initial support for Markdown
roman-rezinkin/RomanStaticSG pull request #17
Opened 2021-09-25 02:48 UTC by Qiwen-Yu

Update and comment code to support the level 1 heading parsing from Mardown file to html file.

2021-09-25 02:49 UTC, Qiwen-Yu commented
The corresponding part of README.md file was also got updated.

2021-09-27 14:27 UTC, humphd commented
@roman-rezinkin it looks like @Qiwen-Yu's PR is ready for review, can you please provide some feedback and merge when ready?

2021-09-27 14:40 UTC, roman-rezinkin requested changes

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/.gitignore
> +# Default ignored files
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/RomanStaticSG.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:40 UTC, roman-rezinkin commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Did you mean to add all the .idea folders? I use JetBrains products and it auto generates them. I am just wondering if it is essential to add these to the code.

2021-09-27 14:41 UTC, humphd commented
If you decide to remove them:

```
git rm -fr .idea
git commit -m "Remove .idea/"
git push origin issue11
```

2021-09-30 01:11 UTC, merged